//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVacationWorkflow.UniversityTerm {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UniversityTerm.IUniversityTermTimes")]
    public interface IUniversityTermTimes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversityTermTimes/GetHolidayDates", ReplyAction="http://tempuri.org/IUniversityTermTimes/GetHolidayDatesResponse")]
        MyVacationWorkflow.UniversityTerm.GetHolidayDatesResponse GetHolidayDates(MyVacationWorkflow.UniversityTerm.GetHolidayDatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversityTermTimes/GetHolidayDates", ReplyAction="http://tempuri.org/IUniversityTermTimes/GetHolidayDatesResponse")]
        System.Threading.Tasks.Task<MyVacationWorkflow.UniversityTerm.GetHolidayDatesResponse> GetHolidayDatesAsync(MyVacationWorkflow.UniversityTerm.GetHolidayDatesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHolidayDates", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetHolidayDatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string university;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string timeOfYear;
        
        public GetHolidayDatesRequest() {
        }
        
        public GetHolidayDatesRequest(string university, string timeOfYear) {
            this.university = university;
            this.timeOfYear = timeOfYear;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHolidayDatesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetHolidayDatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime[] GetHolidayDatesResult;
        
        public GetHolidayDatesResponse() {
        }
        
        public GetHolidayDatesResponse(System.DateTime[] GetHolidayDatesResult) {
            this.GetHolidayDatesResult = GetHolidayDatesResult;
        }
    }
}
