//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVacationWorkflow.AirportTransfer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TravelOption", Namespace="http://schemas.datacontract.org/2004/07/AirportTransferService")]
    [System.SerializableAttribute()]
    public partial class TravelOption : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransportTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationAddress {
            get {
                return this.DestinationAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationAddressField, value) != true)) {
                    this.DestinationAddressField = value;
                    this.RaisePropertyChanged("DestinationAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginAddress {
            get {
                return this.OriginAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginAddressField, value) != true)) {
                    this.OriginAddressField = value;
                    this.RaisePropertyChanged("OriginAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransportType {
            get {
                return this.TransportTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransportTypeField, value) != true)) {
                    this.TransportTypeField = value;
                    this.RaisePropertyChanged("TransportType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AirportTransfer.IAirportTransfer")]
    public interface IAirportTransfer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirportTransfer/GetCheapestTravelOption", ReplyAction="http://tempuri.org/IAirportTransfer/GetCheapestTravelOptionResponse")]
        MyVacationWorkflow.AirportTransfer.GetCheapestTravelOptionResponse GetCheapestTravelOption(MyVacationWorkflow.AirportTransfer.GetCheapestTravelOptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirportTransfer/GetCheapestTravelOption", ReplyAction="http://tempuri.org/IAirportTransfer/GetCheapestTravelOptionResponse")]
        System.Threading.Tasks.Task<MyVacationWorkflow.AirportTransfer.GetCheapestTravelOptionResponse> GetCheapestTravelOptionAsync(MyVacationWorkflow.AirportTransfer.GetCheapestTravelOptionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCheapestTravelOption", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCheapestTravelOptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string originCity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string destinationCity;
        
        public GetCheapestTravelOptionRequest() {
        }
        
        public GetCheapestTravelOptionRequest(string originCity, string destinationCity) {
            this.originCity = originCity;
            this.destinationCity = destinationCity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCheapestTravelOptionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCheapestTravelOptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MyVacationWorkflow.AirportTransfer.TravelOption GetCheapestTravelOptionResult;
        
        public GetCheapestTravelOptionResponse() {
        }
        
        public GetCheapestTravelOptionResponse(MyVacationWorkflow.AirportTransfer.TravelOption GetCheapestTravelOptionResult) {
            this.GetCheapestTravelOptionResult = GetCheapestTravelOptionResult;
        }
    }
}
